
services:
  # MongoDB Service
  mongodb:
    image: mongo:8.0
    container_name: panscience-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - panscience-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: panscience-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - panscience-network

  # Frontend Service (optional - agar Dockerize karna ho)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: panscience-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - panscience-network

volumes:
  mongo-data:
    driver: local

networks:
  panscience-network:
    driver: bridge
